server:
  port: 8080

spring:
  application:
    name: food-order-service

  profiles:
    active: uat

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  ttl: 15m

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 412357480390-1lc2iut4181qe9ine9j8ojjb38b07nsi.apps.googleusercontent.com
            client-secret: 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
            scope: openid, email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub

vnpay:
  tmn-code: CFDFIPZR
  hash-secret: 368Q2N0RNM6C26BM88H8KVAYVSA9VJQC
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/vnpay/payment-return

